<a href="https://colab.research.google.com/github/rj05-ux/customer-segmentation-rfm/blob/main/notebooks/01_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌 Data Cleaning

## Objective

The goal of this notebook is to clean raw transaction data to make it suitable for analysis and modeling.

## Dataset Overview

The dataset contains transactional records from an online retail store, including product details, customer IDs, quantities, and pricing.

## Key Issues in Raw Data

* Missing CustomerID values
* Negative Quantity (product returns)
* Zero or negative UnitPrice
* Incorrect data types (InvoiceDate)

## Cleaning Steps

1. Remove missing CustomerID
2. Remove negative and zero values
3. Convert InvoiceDate to datetime
4. Create TotalPrice feature

## Output

A cleaned dataset ready for analysis and feature engineering.

**STEP 1 — LOAD DATA**

In [1]:
import pandas as pd

df = pd.read_csv('/content/Online Retail Data Set.csv', encoding='ISO-8859-1')

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

**STEP 2 — UNDERSTAND DATA**

In [2]:
df.shape

(541909, 8)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

**STEP 3 — CLEAN DATA**

In [4]:
# Remove missing CustomerID
df = df.dropna(subset=['CustomerID'])

# Remove returns (negative quantity)
df = df[df['Quantity'] > 0]

# Remove invalid price
df = df[df['UnitPrice'] > 0]

**STEP 4 — VERIFY CLEANING**

In [5]:
df.shape
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [7]:
(df['Quantity'] <= 0).sum()
(df['UnitPrice'] <= 0).sum()

np.int64(0)

**STEP 5 — CREATE FEATURE**

In [6]:
df['TotalPrice'] = df['Quantity'] * df['UnitPrice']